name: Build & Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: mozilla-actions/sccache-action@v0.0.7

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
