name: Releaser

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo run -- --repo-url tmayoff/releaser --token ${{ secrets.RELEASER_TOKEN }} pr
